from datetime import datetime
import random
import string
from typing import Dict, List, Optional


class ReadmeFormatter:
    """Formats README content with consistent structure and metadata."""

    def __init__(self, model_name: str):
        """
        Initialize the formatter with the model name.

        Args:
            model_name (str): Name of the model used for generation
        """
        self.model_name = model_name

    def _generate_slug(self) -> str:
        """Generate a 6-character alphanumeric slug."""
        chars = string.ascii_letters + string.digits
        return "".join(random.choice(chars) for _ in range(6))

    def _format_date(self) -> str:
        """Get current date in yyyy-MM-dd HH:mm:ss format."""
        return datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    def format_readme(self, inference_output: str, repo_name: str) -> str:
        """
        Format the inference output into a README with metadata.

        Args:
            inference_output (str): Raw output from the inference service
            repo_name (str): Name of the repository

        Returns:
            str: Formatted README content
        """
        slug = self._generate_slug()

        sections = [
            f"# {repo_name}",
            inference_output,
            "",
            "---",
            f"*Generated by {self.model_name} ({slug}) on {self._format_date()}*",
        ]

        return "\n\n".join(sections)

    def create_prompt(self, repo_path: str) -> str:
        """
        Create a standardized prompt for README generation.

        Args:
            repo_path (str): Path to the repository

        Returns:
            str: Formatted prompt
        """
        return f"""Please analyze this repository and create a README.md file with the following sections:
        - Project Description
        - Key Features
        - Installation
        - Usage
        - Project Structure
        - Contributing Guidelines (if applicable)

        Repository Path: {repo_path}

        Please provide the content in Markdown format without any additional formatting or explanations."""
